### ISSUE TITLE
Missing dependencies 

### ISSUE THREAD

**Issue by polRk** [chiragkataria22/react-final-boilerplate#3]
https://github.com/chiragkataria22/react-final-boilerplate/blob/9039c450bacbe85e26de10a4c99c5c8bfdcf1c3b/webpack/prod/webpack.prod.client.js#L5

**Comment by chiragkataria22** [comment]
Hey @polRk 
Can you please explain more about the issue?
Thanks

**Comment by chiragkataria22** [comment]
hi @polRk 
I have added support for css/scss, if that's what you're looking for.

Thanks

**Comment by polRk** [comment]
Module `optimize-css-assets-webpack-plugin` does not exists in https://github.com/chiragkataria22/react-final-boilerplate/blob/master/package.json

**Comment by chiragkataria22** [comment]
@polRk I am not using it
will remove.
thanks
